package de.unisaarland.cs.se.selab.parser

/**
 * This object holds the keywords of json config files.
 */
object JsonKeys {
    const val ID = "id"
    const val NAME = "name"
    const val TYPE = "type"
    const val CORPORATION = "corporation"
    const val CORPORATIONS = "corporations"
    const val LOCATION = "location"
    const val MAX_VELOCITY = "maxVelocity"
    const val ACCELERATION = "acceleration"
    const val FUEL_CAPACITY = "fuelCapacity"
    const val FUEL_CONSUMPTION = "fuelConsumption"
    const val VISIBILITY_RANGE = "visibilityRange"
    const val GARBAGE_TYPE = "garbageType"
    const val GARBAGE_TYPES = "garbageTypes"
    const val CAPACITY = "capacity"
    const val EVENTS = "events"
    const val TASKS = "tasks"
    const val REWARDS = "rewards"
    const val GARBAGE = "garbage"
    const val TICK = "tick"
    const val DURATION = "duration"
    const val RADIUS = "radius"
    const val SPEED = "speed"
    const val AMOUNT = "amount"
    const val DIRECTION = "direction"
    const val SHIP_ID = "shipID"
    const val SHIPS = "ships"
    const val HOME_HARBORS = "homeHarbors"
    const val TARGET_TILE = "targetTile"
    const val REWARD_ID = "rewardID"
    const val REWARD_SHIP = "rewardShipID"
    const val TILES = "tiles"
    const val COORDINATES = "coordinates"
    const val CATEGORY = "category"
    const val HARBOR = "harbor"
    const val CURRENT = "current"
    const val INTENSITY = "intensity"
    const val X = "x"
    const val Y = "y"
    const val DEEP_OCEAN = "DEEP_OCEAN"
    const val SHALLOW_OCEAN = "SHALLOW_OCEAN"
    const val LAND = "LAND"
    const val SHORE = "SHORE"
    const val PLASTIC = "PLASTIC"
    const val OIL = "OIL"
    const val CHEMICALS = "CHEMICALS"
    const val TELESCOPE = "TELESCOPE"
    const val RADIO = "RADIO"
    const val CONTAINER = "CONTAINER"
    const val TRACKER = "TRACKER"
    const val COLLECT = "COLLECT"
    const val EXPLORE = "EXPLORE"
    const val FIND = "FIND"
    const val COOPERATE = "COOPERATE"
    const val PIRATE_ATTACK = "PIRATE_ATTACK"
    const val OIL_SPILL = "OIL_SPILL"
    const val STORM = "STORM"
    const val RESTRICTION = "RESTRICTION"
    const val TYPHOON = "TYPHOON"

    // From here I've created some extra keys
    const val HARBORS = "harbors"
    const val SHIPYARD_STATION = "shipyardStation"
    const val REFUEL_STATION = "refuelingStation"
    const val UNLOAD_STATION = "unloadingStation"
    const val REPAIR_COST = "repairCost"
    const val SHIP_COST = "shipCost"
    const val DELIVERY_TIME = "deliveryTime"
    const val SHIP_PROP = "shipProperties"
    const val REFUEL_COST = "refuelCost"
    const val REFUEL_TIMES = "refuelTimes"
    const val UNLOAD_RETURN = "unloadReturn"
    const val REFUEL_CAPACITY = "refuelingCapacity"
    const val REFUEL_TIME = "refuelingTime"
    const val HARBOR_ID = "harborID"
    const val CREDITS = "credits"
    const val STRENGTH = "strength"
}
